# Generated by Django 5.1.1 on 2026-01-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='api.genre', verbose_name='Жанр произведения'),
        ),
    ]
